"""
Layer D: Change Tracking
Records every modification made during the pipeline so the UI can display
a clear Before/After comparison and a list of what changed and why.
"""
from app.models import Fix, Section, ParsedDocument, FormattedDocument
from typing import List, Dict, Any


class ChangeTracker:
    """Tracks all changes between original and formatted documents."""

    def __init__(self):
        self.fixes: List[Fix] = []

    def track_changes(
        self,
        document_before: ParsedDocument,
        document_after: FormattedDocument,
    ) -> List[Fix]:
        self.fixes = []

        before_by_id = {s.id: s for s in document_before.sections}

        # Section reordering
        self._track_reordering(document_before, document_after)

        for after_sec in document_after.sections:
            before_sec = before_by_id.get(after_sec.id)
            if before_sec:
                self._track_heading(before_sec, after_sec)
                self._track_font(before_sec, after_sec)
                self._track_content(before_sec, after_sec)
                self._track_type(before_sec, after_sec)
            else:
                # Section was generated (missing section filled by AI)
                self.fixes.append(Fix(
                    section_id=after_sec.id,
                    type="section_generated",
                    original=None,
                    formatted=after_sec.formatted_heading or after_sec.type.value,
                    reason=f"'{after_sec.type.value}' section was missing and was generated by AI",
                ))

        return self.fixes

    # ------------------------------------------------------------------

    def _track_reordering(
        self,
        before: ParsedDocument,
        after: FormattedDocument,
    ) -> None:
        b_pos = {s.id: i for i, s in enumerate(before.sections)}
        a_pos = {s.id: i for i, s in enumerate(after.sections)}

        for sid, a_i in a_pos.items():
            if sid in b_pos and b_pos[sid] != a_i:
                sec = next((s for s in after.sections if s.id == sid), None)
                if sec:
                    self.fixes.append(Fix(
                        section_id=sid,
                        type="section_reordering",
                        original=f"Position {b_pos[sid] + 1}",
                        formatted=f"Position {a_i + 1}",
                        reason=f"'{sec.type.value}' reordered to match IEEE standard sequence",
                    ))

    def _track_heading(self, before: Section, after: Section) -> None:
        if not before.original_heading and after.formatted_heading:
            self.fixes.append(Fix(
                section_id=after.id,
                type="heading_added",
                original=None,
                formatted=after.formatted_heading,
                reason=f"Added IEEE-compliant heading for '{after.type.value}' section",
            ))
        elif (before.original_heading and after.formatted_heading
              and before.original_heading != after.formatted_heading):
            self.fixes.append(Fix(
                section_id=after.id,
                type="heading_formatting",
                original=before.original_heading,
                formatted=after.formatted_heading,
                reason="Applied IEEE heading format: Roman numerals, ALL CAPS, bold styling",
            ))

    def _track_font(self, before: Section, after: Section) -> None:
        if not before.font_rule and after.font_rule:
            fr = after.font_rule
            self.fixes.append(Fix(
                section_id=after.id,
                type="font_formatting",
                original="No font formatting",
                formatted=f"{fr.font_family} {fr.font_size}pt "
                          f"{'Bold' if fr.bold else 'Regular'} "
                          f"{'Italic' if fr.italic else ''} "
                          f"{fr.alignment.capitalize()}",
                reason=f"Applied IEEE font rules for '{after.type.value}'",
            ))

    def _track_content(self, before: Section, after: Section) -> None:
        if before.content != after.content:
            bw = len(before.content.split())
            aw = len(after.content.split())
            diff = aw - bw
            desc = "Grammar and writing improvements applied"
            if diff > 0:
                desc += f" (+{diff} words)"
            elif diff < 0:
                desc += f" ({diff} words)"
            self.fixes.append(Fix(
                section_id=after.id,
                type="grammar_correction",
                original=f"{bw} words",
                formatted=f"{aw} words",
                reason=desc,
            ))

    def _track_type(self, before: Section, after: Section) -> None:
        if before.type != after.type:
            self.fixes.append(Fix(
                section_id=after.id,
                type="section_type_correction",
                original=before.type.value,
                formatted=after.type.value,
                reason="Section type corrected based on heading keywords",
            ))

    def get_fixes_by_type(self, fix_type: str) -> List[Fix]:
        return [f for f in self.fixes if f.type == fix_type]

    def get_summary(self) -> Dict[str, Any]:
        type_counts: Dict[str, int] = {}
        for f in self.fixes:
            type_counts[f.type] = type_counts.get(f.type, 0) + 1
        return {
            "total_changes": len(self.fixes),
            "changes_by_type": type_counts,
            "sections_affected": len({f.section_id for f in self.fixes}),
        }
